server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: TmV2ZXJHb25uYUdpdmVZb3VVcE5ldmVyR29ubmFMZXRZb3VEb3duRm91bmRlckxpbms=
