server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/founderlink_auth
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: TmV2ZXJHb25uYUdpdmVZb3VVcE5ldmVyR29ubmFMZXRZb3VEb3duRm91bmRlckxpbms=
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000
